import { VStack } from '@chakra-ui/react'
import Head from 'next/head'
import MessageBox from '../components/MessageBox'
import Navigation from '../components/Navigation'
import { messages } from '../data/dummy'
export default function Home() {
  return (
    <>
      <Head>
        <title>KC APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <VStack spacing={5} maxW="container.lg" mx="auto" px={4} pb={10}>
        {messages.map((message, index) => (
          <MessageBox key={index} message={message} />
        ))}
      </VStack>
    </>
  )
}
